/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Register;
import java.awt.event.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.*;

/**
 *
 * @author Rock PC
 */
public class RegisterChild extends javax.swing.JFrame {
 JLabel JL_id,JL_name,JL_gender,JL_age;
 JTextField JT_id,JT_name,JT_gender,JT_age;
 JButton btn_insert,btn_update,btn_delete;

    /**
     * Creates new form Register2
     */
    public RegisterChild() {
        
     super("REGISTER CHILD");
     JL_id = new JLabel("ID:");
     JL_name = new JLabel("Name:");
     JL_gender = new JLabel("Gender:");
     JL_age = new JLabel("Age:");
     JL_id.setBounds(20, 20, 100, 20);
     JL_name.setBounds(20, 50, 100, 20);
     JL_gender.setBounds(20, 80, 100, 20);
     JL_age.setBounds(20, 110, 100, 20);
     
     
     JT_id = new JTextField(80);
     JT_name = new JTextField(80);
     JT_gender = new JTextField(80);
     JT_age = new JTextField(80);    
     JT_id.setBounds(130,20,150,30);
     JT_name.setBounds(130, 50, 150, 30);
     JT_gender.setBounds(130, 80, 150, 30);
     JT_age.setBounds(130, 110, 150, 30);
     btn_insert = new JButton("Insert");
     btn_update = new JButton("Update");
     btn_delete = new JButton("Delete");
     btn_insert.setBounds(300, 50, 80, 20);
     btn_update.setBounds(300, 80, 80, 20);
     btn_delete.setBounds(300, 110, 80, 20);
     
     
     setLayout(null);
     add(JL_id);
     add(JL_name);
     add(JL_gender);
     add(JL_age);
     add(JT_id);
     add(JT_name);
     add(JT_gender);
     add(JT_age);
     add(btn_insert);
     add(btn_update);
     add(btn_delete);
     
     


   //button insert
    btn_insert.addActionListener(new  ActionListener() {

         public void actionPerformed(ActionEvent e) {
         try{
             theQuery("insert into child (ID,name,gender,age) values('"+JT_id.getText()+"','"+JT_name.getText()+"','"+JT_gender.getText()+"',"+JT_age.getText()+")");
         }
         catch(Exception ex){}
         }
     });
    
        
     setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
     setVisible(true);
     setLocationRelativeTo(null);
     setSize(500,200);
    
  }
    
    //function to execute the insert update delete query
 
 public void theQuery(String query){
      Connection con = null;
      Statement st = null;
      try{
          con = DriverManager.getConnection("jdbc:mysql://localhost/childreninfo","root","");
          st = con.createStatement();
          st.executeUpdate(query);
          JOptionPane.showMessageDialog(null,"Query Executed");
      }catch(Exception ex){
          JOptionPane.showMessageDialog(null,ex.getMessage());
      }
  }
 
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterChild.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterChild.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterChild.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterChild.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterChild().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
